### ISSUE TITLE
Unable to Manage.

### ISSUE THREAD

**Issue by puresyntax71** [puresyntax71/hugo-theme-chunky-poster#188]
Hi all,

Sorry! I wasn't really able to manage anything in this repo. It's been a tough year. Been busy with both work and life, and recently I've been dealing with the pandemic that has caught up in our place.

I really appreciate, despite a small community, all the help that's been happening in this project even though I haven't really had a chance to answer or review any issues or PRs.

Feel free if you want to fork, manage (message me if you want to), or do whatever you want with the repo.

I've disabled dependabot for lesser noise on the repo. I've also closed all the PRs only related to dependabot. Was originally planning to just remove webpack and use hugo pipes.

Thank you very much!

**Comment by CleanCodeDeveloper** [comment]
Hey, thank you very much for this great template. I really like it and will use it for my private web page. I just created a (private) fork because I need to modify this project for my own needs. By doing so I felt obligated to say thanks for everything you have done so far. May God bless you; I hope life treats you well!
