### ISSUE TITLE
Adding line numbers for prism

### ISSUE THREAD

**Issue by dstudiocontent** [puresyntax71/hugo-theme-chunky-poster#67]
I'm new to Hugo, Is there any way to add line numbers plugin in prismjs?
Thanks for the awesome theme

**Comment by puresyntax71** [comment]
Yeah, so I gave it a try. I guess this is what you can do:

1. Override layouts/partials/foot.html and add the prism-line-numbers.js plugin:

    ```diff
    diff --git a/layouts/partials/foot.html b/layouts/partials/foot.html
    index 5cdc557..bbd0992 100644
    --- a/layouts/partials/foot.html
    +++ b/layouts/partials/foot.html
    @@ -13,6 +13,7 @@
     </script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-core.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/plugins/autoloader/prism-autoloader.min.js"></script>
    +<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/plugins/line-numbers/prism-line-numbers.min.js"></script>
     {{ end }}
     
     {{ range .Site.Params.customJS -}}
    ```

2. Override layouts/_defaults/baseof.html and add the `line-numbers` class to the `body`:

    ```diff
    diff --git a/layouts/_default/baseof.html b/layouts/_default/baseof.html
    index 091995b..6fc38b5 100644
    --- a/layouts/_default/baseof.html
    +++ b/layouts/_default/baseof.html
    @@ -3,7 +3,7 @@
     <head>
         {{ partial "head.html" . }}
     </head>
    -<body>
    +<body class="line-numbers">
         {{ partial "header.html" . }}
     
         {{ block "main" . }}{{ end }}
    ```

3. Add a custom CSS file under the statis/css/file.css, add in the necessary styles from PrismJS and include in the `customCSS` parameter for config.toml.

It looks like this:

![screenshot](https://user-images.githubusercontent.com/34715246/75628927-847d5c00-5c18-11ea-94a5-d2059cbd3e00.png)

The line number styles probably needs to be updated since it seems to conflict with bootstrap's specifically the `font-size` property.

**Comment by dstudiocontent** [comment]
Thank you very much Sir. 😊
